name: Continuous Training Pipeline

# Este pipeline se dispara automáticamente cuando haces push a la rama 'main'
on:
  push:
    branches:
      - main

jobs:
  train_on_gpu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Encender GPU en RunPod y ejecutar DVC
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 
          # Aquí ponemos tu usuario real en la URL
          MLFLOW_TRACKING_URI: "https://dagshub.com/jmvazqueznicolas/drone-detection-mlops.mlflow"
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          pip install runpod --quiet
          
          # 1. Sacamos la llave secreta de la bóveda de GitHub
          echo "${{ secrets.RUNPOD_SSH_PRIVATE_KEY }}" > runpod_key
          
          # 2. Le damos los permisos estrictos de seguridad que exige SSH
          chmod 600 runpod_key
          
          # 3. ¡AHORA SÍ! Arrancamos nuestro orquestador de Python
          python scripts/runpod_orchestrator.py